### ISSUE TITLE
microview fails 

### ISSUE THREAD

**Issue by kennyworkman** [jvfe/kraken2_latch#1]
hello mr jvfe, thanks for your work

this workflow fails at the microview step for the attached tsv, providing the traceback [below:]()

```
 Running MicroView 👓 v0.9.4 




 Found 1 reports... 


/opt/conda/lib/python3.9/site-packages/skbio/stats/ordination/_principal_coordinate_analysis.py:188: RuntimeWarning: invalid value encountered in divide
  proportion_explained = eigvals / sum_eigenvalues
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /opt/conda/lib/python3.9/site-packages/microview/cli.py:75 in main           │
│                                                                              │
│   72 │   │   │   if parsed_result is not None:                               │
│   73 │   │   │   │   tax_plots = generate_taxo_plots(tax_results, parsed_res │
│   74 │   │   │   else:                                                       │
│ ❱ 75 │   │   │   │   tax_plots = generate_taxo_plots(tax_results)            │
│   76 │   │   │   render_base(tax_plots=tax_plots, dir_path=data_source, outp │
│   77 │   │   console.print(f"\n Done!\n", style="bold green")                │
│   78 │   except Exception:                                                   │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │       console = <console width=80 None>                                  │ │
│ │      csv_file = None                                                     │ │
│ │   data_source = PosixPath('/root/tsv_only')                              │ │
│ │        output = PosixPath('/root/microview_report.html')                 │ │
│ │ parsed_result = None                                                     │ │
│ │       reports = [                                                        │ │
│ │                 │   Sample(                                              │ │
│ │                 │   │   report=PosixPath('/root/tsv_only/L01.tsv'),      │ │
│ │                 │   │   report_type='kraken'                             │ │
│ │                 │   )                                                    │ │
│ │                 ]                                                        │ │
│ │   tax_results = {                                                        │ │
│ │                 │   'sample n reads':      index    variable      value  │ │
│ │                 0  L01.tsv    assigned  94.554794                        │ │
│ │                 1  L01.tsv  unassigned   5.445206,                       │ │
│ │                 │   'common taxas':      index                           │ │
│ │                 variable      value                                      │ │
│ │                 1  L01.tsv                    unclassified   5.450000    │ │
│ │                 5  L01.tsv                           other   3.528075    │ │
│ │                 3  L01.tsv              cellular organisms   0.550000    │ │
│ │                 2  L01.tsv              Saccharomycetaceae   0.840000    │ │
│ │                 0  L01.tsv  Saccharomyces cerevisiae S288C  89.180000    │ │
│ │                 4  L01.tsv                   Saccharomyces   0.450000,   │ │
│ │                 │   'abund and div':      index  Shannon Diversity  N    │ │
│ │                 Taxas  Pielou Evenness                                   │ │
│ │                 0  L01.tsv           0.896088     3013         0.111862, │ │
│ │                 │   'beta div':                                          │ │
│ │                 <skbio.stats.ordination._ordination_results.OrdinationR… │ │
│ │                 object at 0x7f4fb1ed6a30>                                │ │
│ │                 }                                                        │ │
│ │      taxonomy = PosixPath('/root/tsv_only')                              │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
│                                                                              │
│ /opt/conda/lib/python3.9/site-packages/microview/plotting.py:134 in          │
│ generate_taxo_plots                                                          │
│                                                                              │
│   131 │   # Beta diversity plots                                             │
│   132 │                                                                      │
│   133 │   pcoa_embed = (                                                     │
│ ❱ 134 │   │   tax_data["beta div"].samples[["PC1", "PC2"]].rename_axis("samp │
│   135 │   )                                                                  │
│   136 │   var_explained = (                                                  │
│   137 │   │   tax_data["beta div"]                                           │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │      assigned = Figure({                                                 │ │
│ │                 │   'data': [{'alignmentgroup': 'True',                  │ │
│ │                 │   │   │     'hovertemplate':                           │ │
│ │                 'Category=assigned<br>Sample name=%{x}<br>% of           │ │
│ │                 reads=%{y}<extra></extra>',                              │ │
│ │                 │   │   │     'legendgroup': 'assigned',                 │ │
│ │                 │   │   │     'marker': {'color': '#636efa', 'pattern':  │ │
│ │                 {'shape': ''}},                                          │ │
│ │                 │   │   │     'name': 'assigned',                        │ │
│ │                 │   │   │     'offsetgroup': 'assigned',                 │ │
│ │                 │   │   │     'orientation': 'v',                        │ │
│ │                 │   │   │     'showlegend': True,                        │ │
│ │                 │   │   │     'textposition': 'auto',                    │ │
│ │                 │   │   │     'type': 'bar',                             │ │
│ │                 │   │   │     'x': array(['L01.tsv'], dtype=object),     │ │
│ │                 │   │   │     'xaxis': 'x',                              │ │
│ │                 │   │   │     'y': array([94.55479444]),                 │ │
│ │                 │   │   │     'yaxis': 'y'},                             │ │
│ │                 │   │   │    {'alignmentgroup': 'True',                  │ │
│ │                 │   │   │     'hovertemplate':                           │ │
│ │                 'Category=unassigned<br>Sample name=%{x}<br>% of         │ │
│ │                 reads=%{y}<extra></extra>',                              │ │
│ │                 │   │   │     'legendgroup': 'unassigned',               │ │
│ │                 │   │   │     'marker': {'color': '#EF553B', 'pattern':  │ │
│ │                 {'shape': ''}},                                          │ │
│ │                 │   │   │     'name': 'unassigned',                      │ │
│ │                 │   │   │     'offsetgroup': 'unassigned',               │ │
│ │                 │   │   │     'orientation': 'v',                        │ │
│ │                 │   │   │     'showlegend': True,                        │ │
│ │                 │   │   │     'textposition': 'auto',                    │ │
│ │                 │   │   │     'type': 'bar',                             │ │
│ │                 │   │   │     'x': array(['L01.tsv'], dtype=object),     │ │
│ │                 │   │   │     'xaxis': 'x',                              │ │
│ │                 │   │   │     'y': array([5.44520556]),                  │ │
│ │                 │   │   │     'yaxis': 'y'}],                            │ │
│ │                 │   'layout': {'barmode': 'relative',                    │ │
│ │                 │   │   │      'legend': {'title': {'text': 'Category'}, │ │
│ │                 'tracegroupgap': 0},                                     │ │
│ │                 │   │   │      'margin': {'t': 60},                      │ │
│ │                 │   │   │      'template': '...',                        │ │
│ │                 │   │   │      'xaxis': {'anchor': 'y',                  │ │
│ │                 │   │   │   │   │   │    'categoryorder': 'category      │ │
│ │                 ascending',                                              │ │
│ │                 │   │   │   │   │   │    'domain': [0.0, 1.0],           │ │
│ │                 │   │   │   │   │   │    'title': {'text': 'Sample       │ │
│ │                 name'}},                                                 │ │
│ │                 │   │   │      'yaxis': {'anchor': 'x', 'domain': [0.0,  │ │
│ │                 1.0], 'title': {'text': '% of reads'}}}                  │ │
│ │                 })                                                       │ │
│ │ assigned_html = '<div>                            <div                   │ │
│ │                 id="assigned-plot" class="plotly-graph-div'+8550         │ │
│ │   contrast_df = None                                                     │ │
│ │      tax_data = {                                                        │ │
│ │                 │   'sample n reads':      index    variable      value  │ │
│ │                 0  L01.tsv    assigned  94.554794                        │ │
│ │                 1  L01.tsv  unassigned   5.445206,                       │ │
│ │                 │   'common taxas':      index                           │ │
│ │                 variable      value                                      │ │
│ │                 1  L01.tsv                    unclassified   5.450000    │ │
│ │                 5  L01.tsv                           other   3.528075    │ │
│ │                 3  L01.tsv              cellular organisms   0.550000    │ │
│ │                 2  L01.tsv              Saccharomycetaceae   0.840000    │ │
│ │                 0  L01.tsv  Saccharomyces cerevisiae S288C  89.180000    │ │
│ │                 4  L01.tsv                   Saccharomyces   0.450000,   │ │
│ │                 │   'abund and div':      index  Shannon Diversity  N    │ │
│ │                 Taxas  Pielou Evenness                                   │ │
│ │                 0  L01.tsv           0.896088     3013         0.111862, │ │
│ │                 │   'beta div':                                          │ │
│ │                 <skbio.stats.ordination._ordination_results.OrdinationR… │ │
│ │                 object at 0x7f4fb1ed6a30>                                │ │
│ │                 }                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
│                                                                              │
│ /opt/conda/lib/python3.9/site-packages/pandas/core/frame.py:3811 in          │
│ __getitem__                                                                  │
│                                                                              │
│    3808 │   │   else:                                                        │
│    3809 │   │   │   if is_iterator(key):                                     │
│    3810 │   │   │   │   key = list(key)                                      │
│ ❱  3811 │   │   │   indexer = self.columns._get_indexer_strict(key, "columns │
│    3812 │   │                                                                │
│    3813 │   │   # take() does not accept boolean indexers                    │
│    3814 │   │   if getattr(indexer, "dtype", None) == bool:                  │
│                                                                              │
│ ╭──────────── locals ────────────╮                                           │
│ │       indexer = None           │                                           │
│ │ is_single_key = False          │                                           │
│ │           key = ['PC1', 'PC2'] │                                           │
│ │          self = │   │    PC1   │                                           │
│ │                 L01.tsv  0.0   │                                           │
│ ╰────────────────────────────────╯                                           │
│                                                                              │
│ /opt/conda/lib/python3.9/site-packages/pandas/core/indexes/base.py:6113 in   │
│ _get_indexer_strict                                                          │
│                                                                              │
│   6110 │   │   else:                                                         │
│   6111 │   │   │   keyarr, indexer, new_indexer = self._reindex_non_unique(k │
│   6112 │   │                                                                 │
│ ❱ 6113 │   │   self._raise_if_missing(keyarr, indexer, axis_name)            │
│   6114 │   │                                                                 │
│   6115 │   │   keyarr = self.take(indexer)                                   │
│   6116 │   │   if isinstance(key, Index):                                    │
│                                                                              │
│ ╭───────────────────── locals ──────────────────────╮                        │
│ │ axis_name = 'columns'                             │                        │
│ │   indexer = array([ 0, -1])                       │                        │
│ │       key = ['PC1', 'PC2']                        │                        │
│ │    keyarr = Index(['PC1', 'PC2'], dtype='object') │                        │
│ │      self = Index(['PC1'], dtype='object')        │                        │
│ ╰───────────────────────────────────────────────────╯                        │
│                                                                              │
│ /opt/conda/lib/python3.9/site-packages/pandas/core/indexes/base.py:6176 in   │
│ _raise_if_missing                                                            │
│                                                                              │
│   6173 │   │   │   │   raise KeyError(f"None of [{key}] are in the [{axis_na │
│   6174 │   │   │                                                             │
│   6175 │   │   │   not_found = list(ensure_index(key)[missing_mask.nonzero() │
│ ❱ 6176 │   │   │   raise KeyError(f"{not_found} not in index")               │
│   6177 │                                                                     │
│   6178 │   @overload                                                         │
│   6179 │   def _get_indexer_non_comparable(                                  │
│                                                                              │
│ ╭───────────────────────── locals ─────────────────────────╮                 │
│ │        axis_name = 'columns'                             │                 │
│ │          indexer = array([ 0, -1])                       │                 │
│ │              key = Index(['PC1', 'PC2'], dtype='object') │                 │
│ │     missing_mask = array([False,  True])                 │                 │
│ │         nmissing = 1                                     │                 │
│ │        not_found = ['PC2']                               │                 │
│ │             self = Index(['PC1'], dtype='object')        │                 │
│ │ use_interval_msg = False                                 │                 │
│ ╰──────────────────────────────────────────────────────────╯                 │
╰──────────────────────────────────────────────────────────────────────────────╯
KeyError: "['PC2'] not in index"
====================
2022-12-05 15:09:13,269 flytekit ERROR Failed to convert return value for var o0 with error <class 'flytekit.exceptions.user.FlyteAssertion'>: Failed to put data from /root/microview_report.html to latch:///kraken2/microview_report.html (recursive=False).


Original exception: [Errno 2] No such file or directory: '/root/microview_report.html'
====================
====================
2022-12-05 15:09:13,270 flytekit.entrypoint ERROR !! Begin System Error Captured by Flyte !!
====================
====================
2022-12-05 15:09:13,270 flytekit.entrypoint ERROR Traceback (most recent call last):


      File "/opt/conda/lib/python3.9/site-packages/flytekit/exceptions/scopes.py", line 166, in system_entry_point
        return wrapped(*args, **kwargs)
      File "/opt/conda/lib/python3.9/site-packages/flytekit/core/base_task.py", line 525, in dispatch_execute
        raise TypeError(


Message:


    Failed to convert return value for var o0 for function wf.__init__.run_microview with error <class 'flytekit.exceptions.user.FlyteAssertion'>: Failed to put data from /root/microview_report.html to latch:///kraken2/microview_report.html (recursive=False).


Original exception: [Errno 2] No such file or directory: '/root/microview_report.html'
```

[L01.tsv.gz](https://github.com/jvfe/kraken2_latch/files/10155974/L01.tsv.gz)

**Comment by jvfe** [comment]
Thanks!

It's an issue with the tool I'm using to visualize the results (which I also develop). But I believe it's fixed now: https://console.latch.bio/explore/83509/info .

There's also a version of this workflow that doesn't use this tool, in case this output isn't necessary: https://console.latch.bio/explore/82006/info
